Repository The-Avengers-kernel/musinsa-server-v1, pull requests merged in 2025-10, with the labels that each got.

#198 [fix][김동균]상품 상세 페이지 구매하기 버튼 완
  src/main/java/com/avengers/musinsa/domain/order/dto/response/OrderPageResponse.java
  src/main/java/com/avengers/musinsa/domain/order/repository/OrderPageRepositoryImpl.java
  src/main/java/com/avengers/musinsa/domain/order/service/OrderPageServiceImpl.java
  src/main/java/com/avengers/musinsa/viewController/OrderPageViewController.java
  src/main/java/com/avengers/musinsa/viewController/OrderViewController.java
  src/main/java/com/avengers/musinsa/viewController/ProductOrderViewController.java
  src/main/resources/mapper/OrderMapper.xml
  src/main/webapp/resources/js/productDetailPage.js
Labels: ⚡️ fix

#196 [조현희] fit: 상품 카테고리 - 중분류 선택 시 검색화면으로 링크이동
  src/main/webapp/resources/js/category.js
Labels: ⚡️ fix

#201 [조현희] 헤더 코드 오류 해결
  src/main/webapp/WEB-INF/views/error.jsp
  src/main/webapp/WEB-INF/views/order/orderPage.jsp
  src/main/webapp/WEB-INF/views/order/test.jsp
  src/main/webapp/WEB-INF/views/product/cart_test.jsp
  src/main/webapp/WEB-INF/views/product/productDetailPage.jsp
  src/main/webapp/WEB-INF/views/shipments/shippingAddressList.jsp
  src/main/webapp/WEB-INF/views/test/testindex.jsp
  src/main/webapp/WEB-INF/views/test/user.jsp
Labels: 🚑 bug

#218 [조현희] 상품 목록 조회 필터링 화면 구현
  src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductServiceImpl.java
  src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
  src/main/java/com/avengers/musinsa/viewController/ProductViewController.java
  src/main/resources/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/product/categoryProductsPage.jsp
  src/main/webapp/WEB-INF/views/product/searchProducts.jsp
  src/main/webapp/resources/css/categoryProductsPage.css
  src/main/webapp/resources/css/search.css
Labels: ✨ feature

#220 [조현희] fix: 브랜드 이미지 크기 조정 및 흑백 반전 적용
  src/main/webapp/resources/css/category.css
  src/main/webapp/resources/css/search.css
Labels: ⚡️ fix

#225 [조현희] fix: 주문 시 재고량 업데이트
  src/main/java/com/avengers/musinsa/domain/order/service/OrderService.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductVariantRepository.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductVariantRepositoryImpl.java
  src/main/java/com/avengers/musinsa/mapper/ProductVariantMapper.java
  src/main/resources/mapper/ProductVariantMapper.xml
Labels: ⚡️ fix

#231 [김동균] 상품 좋아요 유지 기능 및 메인페이지, 카테고리 별 상품 페이지, 검색 상품 페이지 하트 토글기능 완성
  src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductByCategoryResponse.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/RecommendationResponse.java
  src/main/java/com/avengers/musinsa/domain/product/dto/search/SearchResponse.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductServiceImpl.java
  src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
  src/main/java/com/avengers/musinsa/viewController/MainPageViewController.java
  src/main/java/com/avengers/musinsa/viewController/ProductViewController.java
  src/main/resources/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/WEB-INF/views/product/categoryProductsPage.jsp
  src/main/webapp/WEB-INF/views/product/productDetailPage.jsp
  src/main/webapp/WEB-INF/views/product/searchProducts.jsp
  src/main/webapp/resources/css/categoryProductsPage.css
  src/main/webapp/resources/css/search.css
  src/main/webapp/resources/js/common/likeToggle.js
  src/main/webapp/resources/js/productDetailPage.js
Labels: ✨ feature

#227 [박은정] 배송지 추가, 수정,삭제 구현 Feature #184 shippingaddress
  src/main/java/com/avengers/musinsa/domain/shipments/controller/ShippingAddressController.java
  src/main/java/com/avengers/musinsa/domain/shipments/dto/ShippingAddressCreateDTO.java
  src/main/java/com/avengers/musinsa/domain/shipments/repository/ShippingAddressRepository.java
  src/main/java/com/avengers/musinsa/domain/shipments/service/ShippingAddressService.java
  src/main/java/com/avengers/musinsa/mapper/ShippingAddressMapper.java
  src/main/java/com/avengers/musinsa/viewController/ShippingAddressViewController.java
  src/main/resources/mapper/ShippingAddressMapper.xml
  src/main/webapp/WEB-INF/views/shipments/shippingAddressEditForm.jsp
  src/main/webapp/WEB-INF/views/shipments/shippingAddressForm.jsp
  src/main/webapp/WEB-INF/views/shipments/shippingAddressList.jsp
Labels: ✨ feature
