Repository The-Avengers-kernel/musinsa-server-v1, pull requests merged in 2025-09, with the labels that each got.

#43 [김진용] 남성/여성 아이템 추천 상품 목록 조회 구현
  src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/RecommendationResponse.java
  src/main/java/com/avengers/musinsa/domain/product/entity/Gender.java
  src/main/java/com/avengers/musinsa/domain/product/entity/Product.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
  src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
  src/main/resources/mapper/MusinsaMapper.xml
  src/main/resources/mapper/MusinsaServiceMapper.xml
  src/main/resources/mapper/ProductMapper.xml
Labels: ✨ feature

#70 [조현희] feat: 카테고리별 브랜드 목록 조회
  src/main/java/com/avengers/musinsa/domain/brand/controller/BrandController.java
  src/main/java/com/avengers/musinsa/domain/brand/dto/response/BrandByCategoryResponse.java
  src/main/java/com/avengers/musinsa/domain/brand/repository/BrandRepository.java
  src/main/java/com/avengers/musinsa/domain/brand/service/BrandService.java
  src/main/java/com/avengers/musinsa/mapper/BrandMapper.java
  src/main/resources/mapper/BrandMapper.xml
Labels: ✨ feature

#79 [김희재] feat: 최근 브랜드 조회 코드 수정(fix)
  src/main/resources/mapper/BrandMapper.xml
Labels: ⚡️ fix

#81 [김동균] feat: 상품 상세 설명 조회
  src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductDetailDescriptionResponse.java
  src/main/java/com/avengers/musinsa/domain/product/entity/Product.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
  src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
  src/main/resources/mapper/ProductMapper.xml
Labels: ✨ feature

#89 [김동균] feat: 상품 상세 사이즈 리스트
  src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/BottomProductDetailSizeListResponse.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/TopProductDetailSizeListResponse.java
  src/main/java/com/avengers/musinsa/domain/product/entity/BottomSizeDetail.java
  src/main/java/com/avengers/musinsa/domain/product/entity/Product.java
  src/main/java/com/avengers/musinsa/domain/product/entity/Size.java
  src/main/java/com/avengers/musinsa/domain/product/entity/SizeDetailImage.java
  src/main/java/com/avengers/musinsa/domain/product/entity/TopSizeDetails.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
  src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
  src/main/resources/mapper/ProductMapper.xml
Labels: ✨ feature

#91 [김동균] feat: 리뷰 목록 조회
  src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductReviewsResponse.java
  src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
  src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
  src/main/java/com/avengers/musinsa/domain/review/entity/Review.java
  src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
  src/main/resources/mapper/ProductMapper.xml
Labels: ✨ feature

#104 [조현희] refactoring: 메서드명 수정
  src/main/java/com/avengers/musinsa/domain/brand/repository/BrandRepository.java
  src/main/java/com/avengers/musinsa/domain/brand/service/BrandService.java
  src/main/java/com/avengers/musinsa/mapper/BrandMapper.java
  src/main/resources/mapper/BrandMapper.xml
  src/main/resources/mapper/ProductMapper.xml
Labels: 🔨 refactoring

#127 [최민영] 주문서 화면 구현 - 상품 목록, 배송지 주소 조회
  src/main/java/com/avengers/musinsa/domain/main/MainController.java
  src/main/java/com/avengers/musinsa/domain/order/controller/OrderPageController.java
  src/main/java/com/avengers/musinsa/domain/order/dto/request/OrderPageRequest.java
  src/main/java/com/avengers/musinsa/domain/order/dto/response/OrderPageResponse.java
  src/main/java/com/avengers/musinsa/domain/order/repository/OrderPageRepository.java
  src/main/java/com/avengers/musinsa/domain/order/repository/OrderPageRepositoryImpl.java
  src/main/java/com/avengers/musinsa/domain/order/service/OrderPageService.java
  src/main/java/com/avengers/musinsa/domain/order/service/OrderPageServiceImpl.java
  src/main/java/com/avengers/musinsa/domain/order/service/OrderService.java
  src/main/java/com/avengers/musinsa/domain/search/Entity/SearchKeywordLog.java
  src/main/java/com/avengers/musinsa/domain/user/auth/jwt/TokenProviderService.java
  src/main/java/com/avengers/musinsa/mapper/OrderPageMapper.java
  src/main/resources/mapper/OrderPageMapper.xml
Labels: ✨ feature

#110 [박은정] 주문서 배송지 목록 조회
  src/main/java/com/avengers/musinsa/domain/order/controller/OrderController.java
  src/main/java/com/avengers/musinsa/domain/order/repository/OrderRepository.java
  src/main/java/com/avengers/musinsa/domain/order/repository/OrderRepositoryImpl.java
  src/main/java/com/avengers/musinsa/domain/order/service/OrderService.java
  src/main/java/com/avengers/musinsa/domain/shipments/controller/ShippingAddressController.java
  src/main/java/com/avengers/musinsa/domain/shipments/dto/ShippingAddressOrderDTO.java
  src/main/java/com/avengers/musinsa/domain/shipments/repository/ShippingAddressRepository.java
  src/main/java/com/avengers/musinsa/domain/shipments/service/ShippingAddressService.java
  src/main/java/com/avengers/musinsa/mapper/OrderMapper.java
  src/main/java/com/avengers/musinsa/mapper/ShippingAddressMapper.java
  src/main/resources/mapper/OrderMapper.xml
  src/main/resources/mapper/ShippingAddressMapper.xml
Labels: ✨ feature

#140 [조현희] feature: header.jsp
  src/main/webapp/WEB-INF/views/main/header.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/css/header.css
Labels: ✨ feature

#146 [김희재]최근 검색어 및 인기 검색어 조회 인터페이스 추가
  src/main/java/com/avengers/musinsa/domain/search/controller/PopularKeywordController.java
  src/main/java/com/avengers/musinsa/domain/search/controller/RecentSearchesResponseController.java
  src/main/java/com/avengers/musinsa/domain/search/service/PopularKeywordService.java
  src/main/java/com/avengers/musinsa/domain/search/service/PopularKeywordServiceImpl.java
  src/main/java/com/avengers/musinsa/domain/search/service/RecentSearchService.java
  src/main/java/com/avengers/musinsa/domain/search/service/RecentSearchServiceImpl.java
Labels: ⚡️ fix

#153 [최민영] 메인화면 구현
  src/main/java/com/avengers/musinsa/domain/main/MainController.java
  src/main/java/com/avengers/musinsa/domain/order/controller/OrderPageController.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/RecommendationResponse.java
  src/main/java/com/avengers/musinsa/domain/user/auth/oauth2/CustomSuccessHandler.java
  src/main/java/com/avengers/musinsa/domain/user/controller/LoginController.java
  src/main/java/com/avengers/musinsa/viewController/MainPageController.java
  src/main/java/com/avengers/musinsa/viewController/OrderPageViewController.java
  src/main/resources/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/main/header.jsp
  src/main/webapp/WEB-INF/views/main/main.jsp
Labels: ✨ feature

#183 [김동균] 상품상세페이지 수정 완
  src/main/java/com/avengers/musinsa/domain/brand/dto/response/BrandLikeResponse.java
  src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductLikeResponse.java
  src/main/resources/mapper/BrandMapper.xml
  src/main/resources/mapper/CartMapper.xml
  src/main/resources/mapper/ProductMapper.xml
  src/main/webapp/resources/css/productDetailPage.css
  src/main/webapp/resources/js/productDetailPage.js
Labels: ⚡️ fix
